---
- name: "Restart cron"
  become: true
  ansible.builtin.service:
    name: "cron"
    state: restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Rrestart crond"
  become: true
  ansible.builtin.service:
    name: "crond"
    state: restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
